### ISSUE TITLE
Python 3.12 runtime support

### ISSUE THREAD

**Issue by chasegarner** [aws/aws-codebuild-docker-images#690] opened 2023-12-15 02:29 UTC
The official Python 3.12 Lambda image was published recently. When can we expect 3.12 support in CodeBuild images?

**Comment by subinataws** [comment] 2023-12-16 14:00
Duplicate of https://github.com/aws/aws-codebuild-docker-images/issues/677. This runtime version is supported in most latest images in CodeBuild. Arm specific images should get this support in Jan '24.

**Closed by subinataws** 2023-12-16 14:00 UTC
