### ISSUE TITLE
Support for nodejs version 16 & npm 8

### ISSUE THREAD

**Issue by yovko** [aws/aws-codebuild-docker-images#510] opened 2022-01-24 13:16 UTC
The current version of [NodeJS (LTS) is 16](https://nodejs.org/en/).

Could we pls get support for this version (and maybe npm v.8) in the ubuntu-based standard image? Both the npm versions 6 & 7 are legacy releases already according to [https://docs.npmjs.com/cli/v8](https://docs.npmjs.com/cli/v8).

**Comment by subinataws** [comment] 2022-01-24 17:30
@yovko - Thanks for highlighting the issue. This is duplicate of https://github.com/aws/aws-codebuild-docker-images/issues/490, let's track the ask in that issue instead. Resolving.

**Closed by subinataws** 2022-01-24 17:30 UTC
