### ISSUE TITLE
local build takes fooooooreeeevvvvvveeeerrr

### ISSUE THREAD

**Issue by jordanst3wart** [aws/aws-codebuild-docker-images#269] opened 2019-11-19 05:00 UTC
The command `docker build -t aws/codebuild/standard:2.0 .` takes 30 + minutes to run locally for me. I feel like I could create a successful startup in that time, or build alpine linux 100 times over. I feel like storing half the internet in a container is an anti-pattern as well.

Could you simply store the built version here: https://hub.docker.com/u/amazon
Or consider breaking the image into smaller dependencies?

**Comment by jordanst3wart** [comment] 2019-11-19 05:01
If the image is 6GB I might not download it from docker hub, just saying.

**Comment by subinataws** [comment] 2019-11-19 15:13
Duplicate of https://github.com/aws/aws-codebuild-docker-images/issues/152.

**Closed by subinataws** 2019-11-19 15:13 UTC
Labels: duplicate
