### ISSUE TITLE
Support for secondary-artifacts in codebuild_build.sh

### ISSUE THREAD

**Issue by PierreKiwi** [aws/aws-codebuild-docker-images#128] opened 2018-10-11 20:45 UTC
Hello,
I started playing with local CodeBuild builds recently and it looks like the instruction `secondary-artifacts` is not honored.

buildspec.yml
```
version: 0.2

phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/dir1
      - touch file1
      - cd $CODEBUILD_SRC_DIR/dir2
      - touch file2

artifacts:
  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR/dir1
      files:
        - file1
    artifact2:
      base-directory: $CODEBUILD_SRC_DIR/dir2
      files:
        - file2
```

command
```./codebuild_build.sh -i aws/codebuild/python:3.6.5 -a codebuild_build```

output
```
...
agent_1  | [Container] 2018/10/11 20:41:57 Phase context status code: CLIENT_ERROR Message: no definition for primary artifacts in buildspec
agent_1  | [Container] 2018/10/11 20:41:57 Runtime error (*errors.errorString: no definition for primary artifacts in buildspec)
```

If I add a `files` section to `artifacts`, CodeBuild does the zipping of whatever it is specified but secondary artifacts are still not created.

**Comment by zabullet** [comment] 2018-11-16 07:45
This looks like a bug, frankly. Using codeDeploy from console I get the same issue.

This format should be supported as per

https://docs.aws.amazon.com/codebuild/latest/userguide/sample-multi-in-out.html

**Comment by awszhen** [comment] 2018-11-20 23:29
Hi! This is resolved in the latest version of the local agent. SHA: c2dacbc1091a274d587be349075dcec64e5890a58232ed7329c55bd972608a81

**Comment by vibhuyadav** [comment] 2018-12-12 17:52
It is probably unrelated to local agent but I am having the same issue on AWS Codebuild when I only specify secondary artifacts.

![primaryartifactmissing](https://user-images.githubusercontent.com/6370789/49888325-bab09f00-fe0c-11e8-9e36-15d5063cbc4d.PNG)

**Comment by subinataws** [comment] 2018-12-12 18:18
@vibhuyadav - could you please post that error message and the buildspec (remove any sensitive info) on CodeBuild's AWS forums (https://forums.aws.amazon.com/forum.jspa?forumID=230)? Oncalls will take a look.

**Comment by awszhen** [comment] 2018-12-12 18:52
Hi @vibhuyadav , this is the expected behavior. Primary artifacts location is required in local agent. And you can not specify secondary artifacts unless you specify primary artifacts.

**Comment by vibhuyadav** [comment] 2018-12-12 20:43
> Hi @vibhuyadav , this is the expected behavior. Primary artifacts location is required in local agent. And you can not specify secondary artifacts unless you specify primary artifacts.

@awszhen But this is AWS Codebuild and not local agent. I should post this in AWS forums including the buildspec. Thanks @subinataws

**Comment by shduke** [comment] 2019-05-21 04:27
@vibhuyadav did you find a resolution to this? Or do you have a link to your forum post?

**Comment by dean-hsu** [comment] 2019-07-10 00:19
Each artifact identifier under secondary-artifacts block in buildspec.yml must match an artifact defined in the secondaryArtifacts attribute of CodeBuild project.

**Comment by vibhuyadav** [comment] 2019-07-23 16:37
@shduke I did not. For the sake of it I tried again using localbuild and I still see it.
Buildspec -
```
  post_build:
    commands:
      - echo Pre-Build Phase


artifacts:
  secondary-artifacts:
    bin:
      files:
        - deploy/**
      name: bin
      discard-paths: no
```

Error - 
```
agent_1  | [Container] 2019/07/22 20:19:19 Phase complete: UPLOAD_ARTIFACTS State: FAILED
agent_1  | [Container] 2019/07/22 20:19:19 Phase context status code: CLIENT_ERROR Message: no definition for primary artifacts in buildspec
agent_1  | [Container] 2019/07/22 20:19:19 Runtime error (*clienterr.PhaseContextError: no definition for primary artifacts in buildspec)
```

**Comment by solsglasses** [comment] 2019-09-10 16:01
Bump, this is still a problem. Please re-open.  `codebuild_build.sh` is not matching CodeBuild in regards to `secondary-artifacts` config

**Comment by edalongeville** [comment] 2020-05-15 16:41
This is still happening. Could this issue be reopened please ?

**Comment by ShaneGH** [comment] 2020-05-29 12:44
Could be because you are using "secondary-artifacts" instead of "secondary_artifacts".
The documentation is confusing as to the naming conventions

**Comment by kti-chris** [comment] 2020-06-24 22:18
This is due to a bad example in the documentation. This will NOT work:
```
version: 0.2

phases:
build:
  commands:
    - echo Building...
artifacts:
  secondary-artifacts:
    artifact1:
      files:
        - directory/file
      name: secondary-artifact-name-1
    artifact2:
      files:
        - directory/file2
      name: secondary-artifact-name-2
```

The issue is documented here: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

artifacts/files
**Required sequence**. Represents the locations that contain the build output artifacts in the build environment. Contains a sequence of scalars, with each scalar representing a separate location where CodeBuild can find build output artifacts, relative to the original build location or, if set, the base directory.

So this is an edited version that does work:
```
version: 0.2

phases:
build:
  commands:
    - echo Building...
artifacts:
  files:
    - directory/*
  secondary-artifacts:
    artifact1:
      files:
        - directory/file
      name: secondary-artifact-name-1
    artifact2:
      files:
        - directory/file2
      name: secondary-artifact-name-2
```

**Comment by ioMatrix** [comment] 2020-06-24 22:24
This is due to a bad example in the documentation. This will NOT work:
```
version: 0.2

phases:
build:
  commands:
    - echo Building...
artifacts:
  secondary-artifacts:
    artifact1:
      files:
        - directory/file
      name: secondary-artifact-name-1
    artifact2:
      files:
        - directory/file2
      name: secondary-artifact-name-2
```

The documentation, obscurely, points it out: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

artifacts/files
**Required sequence**. Represents the locations that contain the build output artifacts in the build environment. Contains a sequence of scalars, with each scalar representing a separate location where CodeBuild can find build output artifacts, relative to the original build location or, if set, the base directory.

So this is an edited version that does work:
```
version: 0.2

phases:
build:
  commands:
    - echo Building...
artifacts:
  files:
    - directory/*
  secondary-artifacts:
    artifact1:
      files:
        - directory/file
      name: secondary-artifact-name-1
    artifact2:
      files:
        - directory/file2
      name: secondary-artifact-name-2
```

**Comment by datsabk** [comment] 2020-08-29 15:01
This doesn't work for me either. Here's my artifact part of the build spec. 

`artifacts:
  files:
    - '**/*'
  secondary-artifacts: 
    artifact1:
      files: 
        - '**/*'
      base-directory: 'deploy'
      name: 'BuildArtifact'
    artifact2: 
      files: 
        - '**/*'
      base-directory: 'rocketml_orchestration/orc_deploy'
      name: 'OrcArtifact'`

**Comment by gsi-joseespinosa** [comment] 2020-09-24 05:24
> This is due to a bad example in the documentation. This will NOT work:
> 
> ```
> version: 0.2
> 
> phases:
> build:
>   commands:
>     - echo Building...
> artifacts:
>   secondary-artifacts:
>     artifact1:
>       files:
>         - directory/file
>       name: secondary-artifact-name-1
>     artifact2:
>       files:
>         - directory/file2
>       name: secondary-artifact-name-2
> ```
> 
> The documentation, obscurely, points it out: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
> 
> artifacts/files
> **Required sequence**. Represents the locations that contain the build output artifacts in the build environment. Contains a sequence of scalars, with each scalar representing a separate location where CodeBuild can find build output artifacts, relative to the original build location or, if set, the base directory.
> 
> So this is an edited version that does work:
> 
> ```
> version: 0.2
> 
> phases:
> build:
>   commands:
>     - echo Building...
> artifacts:
>   files:
>     - directory/*
>   secondary-artifacts:
>     artifact1:
>       files:
>         - directory/file
>       name: secondary-artifact-name-1
>     artifact2:
>       files:
>         - directory/file2
>       name: secondary-artifact-name-2
> ```

Exactly with this script update build step works. Documentation must to update as well adding missing commands.

**Comment by subinataws** [comment] 2020-09-24 06:16
@ioMatrix @gsi-joseespinosa - Thanks for pointing out the issue with the documentation. We'll get that fixed

**Comment by awszhen** [comment] 2020-09-24 23:23
The documentation in https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html for secondary artifacts has already been updated. Mark this issue as resolved.

**Closed by awszhen** 2020-09-24 23:23 UTC
Labels: CodeBuild-local

**Comment by subinataws** [comment] 2020-09-25 00:03
@gsi-joseespinosa - The buildspec shown in https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html already had the correct syntax. Where did you see the buildspec that had `directory/*` called out instead of `**/*`?

version: 0.2

phases:
build:
  commands:
    - echo Building...
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    artifact1:
      files:
        - directory/file1
      name: secondary-artifact-name-1
    artifact2:
      files:
        - directory/file2
      name: secondary-artifact-name-2

**Comment by ioMatrix** [comment] 2020-09-25 04:35
When I looked at it in Jun it was not correct. I figured it out by reading
the spec and hence my response a few months back. I'm happy it's updated.

**Comment by g-wozniak** [comment] 2021-08-21 11:27
In here [AWS Docs](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-multi-in-out.html) is still invalid

**Comment by strohm-a** [comment] 2021-08-24 20:23
The sample has been corrected.
