### ISSUE TITLE
Local CodeBuild not prints stdout from images

### ISSUE THREAD

**Issue by radengoots** [aws/aws-codebuild-docker-images#66] opened 2018-05-15 08:29 UTC
I try to build locally, but there aren't any stdout from the running image printed for each buildspec command. Was it expected? Do we have an option to turn it on? My debugging process relies on the command output.

Thanks

![screenshot from 2018-05-15 15-22-32](https://user-images.githubusercontent.com/13706443/40045513-b7807764-5854-11e8-8f3f-d63d366c5d6e.png)

**Comment by subinataws** [comment] 2018-05-15 13:53
Duplicate of issue #62. We'll fix this in an upcoming release of local agent. Closing this issue to track log issue in #62.

**Closed by subinataws** 2018-05-15 13:53 UTC
