### ISSUE TITLE
Bintray retirement on 01.05.2021 - Impact on CodeBuild images and CodeBuild jobs

### ISSUE THREAD

**Issue by silvestriluca** [aws/aws-codebuild-docker-images#451] opened 2021-04-13 09:20 UTC
According to [this](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), Bintray is in sunset period and will cease to work on 1st May 2021

SBT is linked on EVERY ubuntu/debian/AmazonLinux based CodeBuild official image, so everytime that a command like `apt-get update` is issued during the build job in `buildspec.yml`, an access to Bintray is done to check for SBT updates. If the repository is not found/accessible, the CodeBuild job will fail.
The [planned maintenance of Bintray on 12.04.2021](https://status.bintray.com/incidents/4mzph0y8l6hk) gave us DevOps a huge heads up, exposing the potential consequences to existing CICD build jobs based on CodeBuild supported images.

After 1st May 2021, once Bintray is shut up, all CodeBuild jobs that issue `apt-get update` will persistently fail, unless AWS updates the official containers in a timely manner to address the issue by providing an alternative repository for SBT.

SBT has a repository migration plan already in motion => https://github.com/sbt/sbt/issues/6294

**Comment by lorengordon** [comment] 2021-04-13 21:08
Duplicate of https://github.com/aws/aws-codebuild-docker-images/issues/449?

**Comment by subinataws** [comment] 2021-04-27 20:29
Addressed in https://github.com/aws/aws-codebuild-docker-images/releases/tag/21.04.23

**Closed by subinataws** 2021-04-27 20:29 UTC
