### ISSUE TITLE
Publish standard image somewhere

### ISSUE THREAD

**Issue by joekiller** [aws/aws-codebuild-docker-images#199] opened 2019-05-07 13:49 UTC
The new standard image build makes me wait for every language to be installed on the image when all I care about is likely one or two. This eats into my time as I want to test builds. I'd like to imagine that the build is "once in a while" but that'll likely be untrue. Can you all publish a public ECR url or something so developers don't burn time making the catchall image?

**Comment by subinataws** [comment] 2019-05-07 14:09
@joekiller - Thanks for the feedback. We are aware of the ask to have the pre-built version available in a publicly available Docker registry to derive from or to directly use them. We will do that when we have Amazon Linux 2 based images. For Ubuntu based images, we will only be providing Dockerfile for reference.

**Comment by subinataws** [comment] 2019-05-09 05:49
Duplicate of https://github.com/aws/aws-codebuild-docker-images/issues/152. Let's track this request there.

**Closed by subinataws** 2019-05-09 05:49 UTC
Labels: duplicate
