### ISSUE TITLE
[URGENT] Looking forward to add support for DotNET 8.0 in CodeBuild.

### ISSUE THREAD

**Issue by kumail-raza** [aws/aws-codebuild-docker-images#688] opened 2023-12-10 08:42 UTC
I am looking forward to adding the support of DotNET 8.0 across AWS runtime and platforms. 
Kindly share the plans as we are likely to launch an application in a production environment.
Require same for the QA/Stage, however to avoid delay we tried with alternative approaches.

**Comment by Dylan-AWS** [comment] 2023-12-14 19:45
We released .NET 8.0 in the AL:5.0 image and Ubuntu 7.0 (#689). 
Closing this issue as it is a duplicate of #685

**Closed by Dylan-AWS** 2023-12-14 19:45 UTC
