### ISSUE TITLE
Source URIs to pull these built images locally?

### ISSUE THREAD

**Issue by athewsey** [aws/aws-codebuild-docker-images#457] opened 2021-05-11 07:01 UTC
Hi all,

I'm looking to build a customized CodeBuild docker container, but thought inheriting from one of the AWS-maintained images might give a better base than building from scratch.

With the AWS Deep Learning containers, there's a [published list of ECR repositories](https://github.com/aws/deep-learning-containers/blob/master/available_images.md) from which available containers can be pulled - meaning my dockerfile can start with `FROM xyz.dkr.ap-southeast-1.amazonaws.com/...` and the build can be nice and simple.

...But I could only find relative identifiers in the [CodeBuild docs](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html), can't see listings from verified accounts on [ECR public](https://gallery.ecr.aws/) and couldn't find examples on this repo either.

Are these images available publicly anywhere for us to use as parents? Or do we need to build them from source to use them?

**Comment by subinataws** [comment] 2021-05-20 17:59
Duplicate of https://github.com/aws/aws-codebuild-docker-images/issues/411. Please track on the linked issue.

**Closed by subinataws** 2021-05-20 17:59 UTC
